[
  {
    "Target": "Pipfile.lock",
    "Type": "pipenv",
    "Vulnerabilities": [
      {
        "VulnerabilityID": "CVE-2021-33026",
        "PkgName": "flask-caching",
        "InstalledVersion": "1.4.0",
        "Layer": {
          "DiffID": "sha256:200064bdef5e76f500ad63d56e0c98917c5cb3b2b980f4cec6dad3eb961472fa"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2021-33026",
        "Title": "The Flask-Caching extension through 1.10.1 for Flask relies on Pickle for serialization, which may lead to remote code execution or local privilege escalation. If an attacker gains access to cache storage (e.g., filesystem, Memcached, Redis, etc.), they can construct a crafted payload, poison the cache, and execute Python code.",
        "Description": "The Flask-Caching extension through 1.10.1 for Flask relies on Pickle for serialization, which may lead to remote code execution or local privilege escalation. If an attacker gains access to cache storage (e.g., filesystem, Memcached, Redis, etc.), they can construct a crafted payload, poison the cache, and execute Python code.",
        "Severity": "CRITICAL",
        "CweIDs": [
          "CWE-269"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "V2Score": 7.5,
            "V3Score": 9.8
          }
        },
        "References": [
          "https://github.com/sh4nks/flask-caching/pull/209"
        ],
        "PublishedDate": "2021-05-13T23:15:00Z",
        "LastModifiedDate": "2021-05-24T14:35:00Z"
      },
      {
        "VulnerabilityID": "CVE-2020-25032",
        "PkgName": "flask-cors",
        "InstalledVersion": "3.0.6",
        "FixedVersion": "3.0.9",
        "Layer": {
          "DiffID": "sha256:200064bdef5e76f500ad63d56e0c98917c5cb3b2b980f4cec6dad3eb961472fa"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-25032",
        "Title": "python-flask-cors: allows ../ directory traversal to access private resources",
        "Description": "An issue was discovered in Flask-CORS (aka CORS Middleware for Flask) before 3.0.9. It allows ../ directory traversal to access private resources because resource matching does not ensure that pathnames are in a canonical format.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-1188"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
            "V2Score": 5,
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
            "V3Score": 7.5
          }
        },
        "References": [
          "http://lists.opensuse.org/opensuse-security-announce/2020-09/msg00028.html",
          "http://lists.opensuse.org/opensuse-security-announce/2020-09/msg00032.html",
          "http://lists.opensuse.org/opensuse-security-announce/2020-09/msg00039.html",
          "http://lists.opensuse.org/opensuse-security-announce/2020-09/msg00048.html",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-25032",
          "https://github.com/advisories/GHSA-xc3p-ff3m-f46v",
          "https://github.com/corydolphin/flask-cors/releases/tag/3.0.9",
          "https://nvd.nist.gov/vuln/detail/CVE-2020-25032",
          "https://www.debian.org/security/2020/dsa-4775"
        ],
        "PublishedDate": "2020-08-31T04:15:00Z",
        "LastModifiedDate": "2020-10-21T12:15:00Z"
      },
      {
        "VulnerabilityID": "pyup.io-40104",
        "PkgName": "gunicorn",
        "InstalledVersion": "19.9.0",
        "FixedVersion": "19.10.0, 20.0.1",
        "Layer": {
          "DiffID": "sha256:200064bdef5e76f500ad63d56e0c98917c5cb3b2b980f4cec6dad3eb961472fa"
        },
        "Title": "Gunicorn 20.0.1 fixes chunked encoding support to prevent any request smuggling for security purposes.",
        "Severity": "UNKNOWN"
      },
      {
        "VulnerabilityID": "pyup.io-40105",
        "PkgName": "gunicorn",
        "InstalledVersion": "19.9.0",
        "FixedVersion": "19.10.0",
        "Layer": {
          "DiffID": "sha256:200064bdef5e76f500ad63d56e0c98917c5cb3b2b980f4cec6dad3eb961472fa"
        },
        "Title": "Gunicorn 19.10.0 includes a security fix to prevent HTTP desync attack.",
        "Severity": "UNKNOWN"
      },
      {
        "VulnerabilityID": "CVE-2019-10906",
        "PkgName": "jinja2",
        "InstalledVersion": "2.10",
        "FixedVersion": "2.10.1",
        "Layer": {
          "DiffID": "sha256:200064bdef5e76f500ad63d56e0c98917c5cb3b2b980f4cec6dad3eb961472fa"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-10906",
        "Title": "python-jinja2: str.format_map allows sandbox escape",
        "Description": "In Pallets Jinja before 2.10.1, str.format_map allows a sandbox escape.",
        "Severity": "HIGH",
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
            "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:N/A:N",
            "V2Score": 5,
            "V3Score": 8.6
          },
          "redhat": {
            "V3Vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:C/C:H/I:H/A:H",
            "V3Score": 9
          }
        },
        "References": [
          "http://lists.opensuse.org/opensuse-security-announce/2019-05/msg00030.html",
          "http://lists.opensuse.org/opensuse-security-announce/2019-06/msg00064.html",
          "https://access.redhat.com/errata/RHSA-2019:1152",
          "https://access.redhat.com/errata/RHSA-2019:1237",
          "https://access.redhat.com/errata/RHSA-2019:1329",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-10906",
          "https://github.com/advisories/GHSA-462w-v97r-4m45",
          "https://linux.oracle.com/cve/CVE-2019-10906.html",
          "https://linux.oracle.com/errata/ELSA-2019-1152.html",
          "https://lists.apache.org/thread.html/09fc842ff444cd43d9d4c510756fec625ef8eb1175f14fd21de2605f@%3Cdevnull.infra.apache.org%3E",
          "https://lists.apache.org/thread.html/2b52b9c8b9d6366a4f1b407a8bde6af28d9fc73fdb3b37695fd0d9ac@%3Cdevnull.infra.apache.org%3E",
          "https://lists.apache.org/thread.html/320441dccbd9a545320f5f07306d711d4bbd31ba43dc9eebcfc602df@%3Cdevnull.infra.apache.org%3E",
          "https://lists.apache.org/thread.html/46c055e173b52d599c648a98199972dbd6a89d2b4c4647b0500f2284@%3Cdevnull.infra.apache.org%3E",
          "https://lists.apache.org/thread.html/57673a78c4d5c870d3f21465c7e2946b9f8285c7c57e54c2ae552f02@%3Ccommits.airflow.apache.org%3E",
          "https://lists.apache.org/thread.html/7f39f01392d320dfb48e4901db68daeece62fd60ef20955966739993@%3Ccommits.airflow.apache.org%3E",
          "https://lists.apache.org/thread.html/b2380d147b508bbcb90d2cad443c159e63e12555966ab4f320ee22da@%3Ccommits.airflow.apache.org%3E",
          "https://lists.apache.org/thread.html/f0c4a03418bcfe70c539c5dbaf99c04c98da13bfa1d3266f08564316@%3Ccommits.airflow.apache.org%3E",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DSW3QZMFVVR7YE3UT4YRQA272TYAL5AF/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/QCDYIS254EJMBNWOG4S5QY6AOTOR4TZU/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/TS7IVZAJBWOHNRDMFJDIZVFCMRP6YIUQ/",
          "https://nvd.nist.gov/vuln/detail/CVE-2019-10906",
          "https://palletsprojects.com/blog/jinja-2-10-1-released",
          "https://palletsprojects.com/blog/jinja-2-10-1-released/",
          "https://ubuntu.com/security/notices/USN-4011-1",
          "https://ubuntu.com/security/notices/USN-4011-2",
          "https://usn.ubuntu.com/4011-1/",
          "https://usn.ubuntu.com/4011-2/"
        ],
        "PublishedDate": "2019-04-07T00:29:00Z",
        "LastModifiedDate": "2020-08-24T17:37:00Z"
      },
      {
        "VulnerabilityID": "CVE-2020-28493",
        "PkgName": "jinja2",
        "InstalledVersion": "2.10",
        "FixedVersion": "2.11.3",
        "Layer": {
          "DiffID": "sha256:200064bdef5e76f500ad63d56e0c98917c5cb3b2b980f4cec6dad3eb961472fa"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-28493",
        "Title": "python-jinja2: ReDOS vulnerability due to the sub-pattern",
        "Description": "This affects the package jinja2 from 0.0.0 and before 2.11.3. The ReDoS vulnerability is mainly due to the `_punctuation_re regex` operator and its use of multiple wildcards. The last wildcard is the most exploitable as it searches for trailing punctuation. This issue can be mitigated by Markdown to format user content instead of the urlize filter, or by implementing request timeouts and limiting process memory.",
        "Severity": "MEDIUM",
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
            "V2Score": 5,
            "V3Score": 5.3
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
            "V3Score": 7.5
          }
        },
        "References": [
          "https://github.com/advisories/GHSA-g3rq-g295-4j3m",
          "https://github.com/pallets/jinja/blob/ab81fd9c277900c85da0c322a2ff9d68a235b2e6/src/jinja2/utils.py%23L20",
          "https://github.com/pallets/jinja/pull/1343",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/PVAKCOO7VBVUBM3Q6CBBTPBFNP5NDXF4/",
          "https://nvd.nist.gov/vuln/detail/CVE-2020-28493",
          "https://snyk.io/vuln/SNYK-PYTHON-JINJA2-1012994"
        ],
        "PublishedDate": "2021-02-01T20:15:00Z",
        "LastModifiedDate": "2021-03-22T16:34:00Z"
      },
      {
        "VulnerabilityID": "CVE-2017-18342",
        "PkgName": "pyyaml",
        "InstalledVersion": "3.13",
        "FixedVersion": "4.1",
        "Layer": {
          "DiffID": "sha256:200064bdef5e76f500ad63d56e0c98917c5cb3b2b980f4cec6dad3eb961472fa"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2017-18342",
        "Title": "PyYAML: yaml.load() API could execute arbitrary code",
        "Description": "In PyYAML before 5.1, the yaml.load() API could execute arbitrary code if used with untrusted data. The load() function has been deprecated in version 5.1 and the 'UnsafeLoader' has been introduced for backward compatibility with the function.",
        "Severity": "CRITICAL",
        "CweIDs": [
          "CWE-502"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "V2Score": 7.5,
            "V3Score": 9.8
          },
          "redhat": {
            "V3Vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "V3Score": 8.1
          }
        },
        "References": [
          "https://github.com/advisories/GHSA-rprw-h62v-c2w7",
          "https://github.com/marshmallow-code/apispec/issues/278",
          "https://github.com/yaml/pyyaml/blob/master/CHANGES",
          "https://github.com/yaml/pyyaml/issues/193",
          "https://github.com/yaml/pyyaml/pull/74",
          "https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/JEX7IPV5P2QJITAMA5Z63GQCZA5I6NVZ/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KSQQMRUQSXBSUXLCRD3TSZYQ7SEZRKCE/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/M6JCFGEIEOFMWWIXGHSELMKQDD4CV2BA/",
          "https://nvd.nist.gov/vuln/detail/CVE-2017-18342",
          "https://security.gentoo.org/glsa/202003-45"
        ],
        "PublishedDate": "2018-06-27T12:29:00Z",
        "LastModifiedDate": "2020-10-14T13:23:00Z"
      },
      {
        "VulnerabilityID": "CVE-2020-14343",
        "PkgName": "pyyaml",
        "InstalledVersion": "3.13",
        "FixedVersion": "5.4",
        "Layer": {
          "DiffID": "sha256:200064bdef5e76f500ad63d56e0c98917c5cb3b2b980f4cec6dad3eb961472fa"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-14343",
        "Title": "PyYAML: incomplete fix for CVE-2020-1747",
        "Description": "A vulnerability was discovered in the PyYAML library in versions before 5.4, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. This flaw allows an attacker to execute arbitrary code on the system by abusing the python/object/new constructor. This flaw is due to an incomplete fix for CVE-2020-1747.",
        "Severity": "CRITICAL",
        "CweIDs": [
          "CWE-20"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:C/I:C/A:C",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "V2Score": 10,
            "V3Score": 9.8
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "V3Score": 9.8
          }
        },
        "References": [
          "https://bugzilla.redhat.com/show_bug.cgi?id=1860466",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-14343",
          "https://github.com/advisories/GHSA-8q59-q68h-6hv4",
          "https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation",
          "https://nvd.nist.gov/vuln/detail/CVE-2020-14343",
          "https://ubuntu.com/security/notices/USN-4940-1"
        ],
        "PublishedDate": "2021-02-09T21:15:00Z",
        "LastModifiedDate": "2021-02-16T16:22:00Z"
      },
      {
        "VulnerabilityID": "CVE-2020-1747",
        "PkgName": "pyyaml",
        "InstalledVersion": "3.13",
        "FixedVersion": "5.3.1",
        "Layer": {
          "DiffID": "sha256:200064bdef5e76f500ad63d56e0c98917c5cb3b2b980f4cec6dad3eb961472fa"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-1747",
        "Title": "PyYAML: arbitrary command execution through python/object/new when FullLoader is used",
        "Description": "A vulnerability was discovered in the PyYAML library in versions before 5.3.1, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. An attacker could use this flaw to execute arbitrary code on the system by abusing the python/object/new constructor.",
        "Severity": "CRITICAL",
        "CweIDs": [
          "CWE-20"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:C/I:C/A:C",
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "V2Score": 10,
            "V3Score": 9.8
          },
          "redhat": {
            "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "V3Score": 9.8
          }
        },
        "References": [
          "http://lists.opensuse.org/opensuse-security-announce/2020-04/msg00017.html",
          "http://lists.opensuse.org/opensuse-security-announce/2020-05/msg00017.html",
          "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2020-1747",
          "https://github.com/advisories/GHSA-6757-jp84-gxfx",
          "https://github.com/yaml/pyyaml/pull/386",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/7PPAS6C4SZRDQLR7C22A5U3QOLXY33JX/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/K5HEPD7LEVDPCITY5IMDYWXUMX37VFMY/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MMQXSZXNJT6ERABJZAAICI3DQSQLCP3D/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/WORRFHPQVAFKKXXWLSSW6XKUYLWM6CSH/",
          "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/ZBJA3SGNJKCAYPSHOHWY3KBCWNM5NYK2/",
          "https://nvd.nist.gov/vuln/detail/CVE-2020-1747"
        ],
        "PublishedDate": "2020-03-24T15:15:00Z",
        "LastModifiedDate": "2021-03-26T02:44:00Z"
      },
      {
        "VulnerabilityID": "CVE-2019-7164",
        "PkgName": "sqlalchemy",
        "InstalledVersion": "1.2.9",
        "FixedVersion": "1.3.0",
        "Layer": {
          "DiffID": "sha256:200064bdef5e76f500ad63d56e0c98917c5cb3b2b980f4cec6dad3eb961472fa"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-7164",
        "Title": "python-sqlalchemy: SQL Injection when the order_by parameter can be controlled",
        "Description": "SQLAlchemy through 1.2.17 and 1.3.x through 1.3.0b2 allows SQL Injection via the order_by parameter.",
        "Severity": "CRITICAL",
        "CweIDs": [
          "CWE-89"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:P/I:P/A:P",
            "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "V2Score": 7.5,
            "V3Score": 9.8
          },
          "redhat": {
            "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L",
            "V3Score": 7.3
          }
        },
        "References": [
          "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00087.html",
          "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00010.html",
          "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00016.html",
          "https://access.redhat.com/errata/RHSA-2019:0981",
          "https://access.redhat.com/errata/RHSA-2019:0984",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-7164",
          "https://github.com/advisories/GHSA-887w-45rq-vxgf",
          "https://github.com/sqlalchemy/sqlalchemy/issues/4481",
          "https://linux.oracle.com/cve/CVE-2019-7164.html",
          "https://linux.oracle.com/errata/ELSA-2019-0984.html",
          "https://lists.debian.org/debian-lts-announce/2019/03/msg00020.html",
          "https://nvd.nist.gov/vuln/detail/CVE-2019-7164",
          "https://www.oracle.com/security-alerts/cpujan2021.html"
        ],
        "PublishedDate": "2019-02-20T00:29:00Z",
        "LastModifiedDate": "2021-01-20T15:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2019-7548",
        "PkgName": "sqlalchemy",
        "InstalledVersion": "1.2.9",
        "FixedVersion": "1.3.0",
        "Layer": {
          "DiffID": "sha256:200064bdef5e76f500ad63d56e0c98917c5cb3b2b980f4cec6dad3eb961472fa"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-7548",
        "Title": "python-sqlalchemy: SQL Injection when the group_by parameter can be controlled",
        "Description": "SQLAlchemy 1.2.17 has SQL Injection when the group_by parameter can be controlled.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-89"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
            "V3Vector": "CVSS:3.0/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
            "V2Score": 6.8,
            "V3Score": 7.8
          },
          "redhat": {
            "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L",
            "V3Score": 7.3
          }
        },
        "References": [
          "http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00087.html",
          "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00010.html",
          "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00016.html",
          "https://access.redhat.com/errata/RHSA-2019:0981",
          "https://access.redhat.com/errata/RHSA-2019:0984",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-7548",
          "https://github.com/advisories/GHSA-38fc-9xqv-7f7q",
          "https://github.com/no-security/sqlalchemy_test",
          "https://github.com/sqlalchemy/sqlalchemy/issues/4481#issuecomment-461204518",
          "https://linux.oracle.com/cve/CVE-2019-7548.html",
          "https://linux.oracle.com/errata/ELSA-2019-0984.html",
          "https://lists.debian.org/debian-lts-announce/2019/03/msg00020.html",
          "https://nvd.nist.gov/vuln/detail/CVE-2019-7548",
          "https://www.oracle.com/security-alerts/cpujan2021.html"
        ],
        "PublishedDate": "2019-02-06T21:29:00Z",
        "LastModifiedDate": "2021-01-20T15:15:00Z"
      },
      {
        "VulnerabilityID": "CVE-2019-9710",
        "PkgName": "webargs",
        "InstalledVersion": "3.0.2",
        "FixedVersion": "5.1.3",
        "Layer": {
          "DiffID": "sha256:200064bdef5e76f500ad63d56e0c98917c5cb3b2b980f4cec6dad3eb961472fa"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-9710",
        "Title": "webargs 5.1.3 fixes race condition between parallel requests when the cache is used. See: CVE-2019-9710.",
        "Description": "An issue was discovered in webargs before 5.1.3, as used with marshmallow and other products. JSON parsing uses a short-lived cache to store the parsed JSON body. This cache is not thread-safe, meaning that incorrect JSON payloads could have been parsed for concurrent requests.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-362"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:M/Au:N/C:P/I:P/A:P",
            "V3Vector": "CVSS:3.0/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H",
            "V2Score": 6.8,
            "V3Score": 8.1
          }
        },
        "References": [
          "https://github.com/advisories/GHSA-8554-jxcw-454q",
          "https://github.com/marshmallow-code/webargs/issues/371",
          "https://nvd.nist.gov/vuln/detail/CVE-2019-9710",
          "https://webargs.readthedocs.io/en/latest/changelog.html"
        ],
        "PublishedDate": "2019-03-12T02:29:00Z",
        "LastModifiedDate": "2019-03-12T13:09:00Z"
      },
      {
        "VulnerabilityID": "CVE-2019-14806",
        "PkgName": "werkzeug",
        "InstalledVersion": "0.14.1",
        "FixedVersion": "0.15.3",
        "Layer": {
          "DiffID": "sha256:200064bdef5e76f500ad63d56e0c98917c5cb3b2b980f4cec6dad3eb961472fa"
        },
        "SeveritySource": "nvd",
        "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-14806",
        "Title": "python-werkzeug: insufficient debugger PIN randomness vulnerability",
        "Description": "Pallets Werkzeug before 0.15.3, when used with Docker, has insufficient debugger PIN randomness because Docker containers share the same machine id.",
        "Severity": "HIGH",
        "CweIDs": [
          "CWE-331"
        ],
        "CVSS": {
          "nvd": {
            "V2Vector": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
            "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
            "V2Score": 5,
            "V3Score": 7.5
          },
          "redhat": {
            "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
            "V3Score": 7.5
          }
        },
        "References": [
          "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00034.html",
          "http://lists.opensuse.org/opensuse-security-announce/2019-09/msg00047.html",
          "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-14806",
          "https://github.com/advisories/GHSA-gq9m-qvpx-68hc",
          "https://github.com/pallets/werkzeug/blob/7fef41b120327d3912fbe12fb64f1951496fcf3e/src/werkzeug/debug/__init__.py#L168",
          "https://github.com/pallets/werkzeug/commit/00bc43b1672e662e5e3b8cecd79e67fc968fa246",
          "https://nvd.nist.gov/vuln/detail/CVE-2019-14806",
          "https://palletsprojects.com/blog/werkzeug-0-15-3-released/",
          "https://ubuntu.com/security/notices/USN-4655-1"
        ],
        "PublishedDate": "2019-08-09T15:15:00Z",
        "LastModifiedDate": "2019-09-11T00:15:00Z"
      },
      {
        "VulnerabilityID": "pyup.io-36967",
        "PkgName": "werkzeug",
        "InstalledVersion": "0.14.1",
        "FixedVersion": "0.15.0",
        "Layer": {
          "DiffID": "sha256:200064bdef5e76f500ad63d56e0c98917c5cb3b2b980f4cec6dad3eb961472fa"
        },
        "Title": "Werkzeug 0.15.0 refactors class:`~middleware.proxy_fix.ProxyFix` to support more headers, multiple values, and a more secure configuration.",
        "Severity": "UNKNOWN"
      }
    ]
  }
]